# Dockerfile.node
FROM node:18-alpine

# Configurar directorio de trabajo
WORKDIR /app

# Copiar los archivos de dependencias primero
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto del código
COPY . .

# Exponer el puerto
EXPOSE 8002

# Comando para ejecutar en modo desarrollo
CMD ["npm", "run", "dev"]