# Dockerfile.react
FROM node:18-alpine as build
WORKDIR /app
COPY ./app/front/client ./front/client
WORKDIR /app/front/client
RUN npm install
RUN npm run build

FROM node:18-alpine
#WORKDIR /app
RUN npm install -g serve
COPY --from=build /app/front/client/dist /app/dist
EXPOSE 80
CMD ["serve", "-s", "/app/dist", "-l", "80", "--single"]