version: '3.8'

services:
  iakata:
    build: 
      context: .
      dockerfile: Dockerfile
    cap_add:
      - SYS_PTRACE  # Permite depuración y seguimiento de procesos
      - DAC_READ_SEARCH  # Permite leer archivos que normalmente requerirían más permisos
    volumes:
      - .:/app
      - iakata_vectors:/app/vectorstore/processed/vectors
      - iakata_cache:/app/vectorstore/cache
      - iakata_logs:/app/logs
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - DEBUG=True
    networks:
      - iakata_network
      
  # Servicio FastAPI RAG
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "8001:8001"
    networks:
      - iakata_network
    volumes:
      - ./app/api:/app

networks:
  iakata_network:
    driver: bridge

volumes:
  iakata_vectors:
  iakata_cache:
  iakata_logs: